services:
  - type: web
    name: toxicity-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/app.py"
    plan: free
    envVars:
      - key: PORT
        value: 10000

staticSites:
  - name: toxicity-frontend
    buildCommand: ""
    staticPublishPath: frontend
    indexDocument: index.html
